package luxtronik

func NewCalculationsMap() DataTypeMap {
	return DataTypeMap{
		// the index number is really import because it assigns a value from the
		// heat pump to the Base object. The heat pump only sends the values
		// from 0 to 1053.
		0:   NewUnknown("Unknown_Calculation_0"),
		1:   NewUnknown("Unknown_Calculation_1"),
		2:   NewUnknown("Unknown_Calculation_2"),
		3:   NewUnknown("Unknown_Calculation_3"),
		4:   NewUnknown("Unknown_Calculation_4"),
		5:   NewUnknown("Unknown_Calculation_5"),
		6:   NewUnknown("Unknown_Calculation_6"),
		7:   NewUnknown("Unknown_Calculation_7"),
		8:   NewUnknown("Unknown_Calculation_8"),
		9:   NewUnknown("Unknown_Calculation_9"),
		10:  NewCelsius("ID_WEB_Temperatur_TVL", false), // vorlauf
		11:  NewCelsius("ID_WEB_Temperatur_TRL", false), // ruecklauf
		12:  NewCelsius("ID_WEB_Sollwert_TRL_HZ", false),
		13:  NewCelsius("ID_WEB_Temperatur_TRL_ext", false),
		14:  NewCelsius("ID_WEB_Temperatur_THG", false),
		15:  NewCelsius("ID_WEB_Temperatur_TA", false),    // outdoor temp
		16:  NewCelsius("ID_WEB_Mitteltemperatur", false), // avg outdoor temp
		17:  NewCelsius("ID_WEB_Temperatur_TBW", false),   // DHW current temp
		18:  NewCelsius("ID_WEB_Einst_BWS_akt", false),    // DHW target temp
		19:  NewCelsius("ID_WEB_Temperatur_TWE", false),
		20:  NewCelsius("ID_WEB_Temperatur_TWA", false),
		21:  NewCelsius("ID_WEB_Temperatur_TFB1", false),
		22:  NewCelsius("ID_WEB_Sollwert_TVL_MK1", false),
		23:  NewCelsius("ID_WEB_Temperatur_RFV", false),
		24:  NewCelsius("ID_WEB_Temperatur_TFB2", false),
		25:  NewCelsius("ID_WEB_Sollwert_TVL_MK2", false),
		26:  NewCelsius("ID_WEB_Temperatur_TSK", false),
		27:  NewCelsius("ID_WEB_Temperatur_TSS", false),
		28:  NewCelsius("ID_WEB_Temperatur_TEE", false),
		29:  NewBool("ID_WEB_ASDin", false),
		30:  NewBool("ID_WEB_BWTin", false),
		31:  NewBool("ID_WEB_EVUin", false),
		32:  NewBool("ID_WEB_HDin", false),
		33:  NewBool("ID_WEB_MOTin", false),
		34:  NewBool("ID_WEB_NDin", false),
		35:  NewBool("ID_WEB_PEXin", false),
		36:  NewBool("ID_WEB_SWTin", false),
		37:  NewBool("ID_WEB_AVout", false),
		38:  NewBool("ID_WEB_BUPout", false),
		39:  NewBool("ID_WEB_HUPout", false),
		40:  NewBool("ID_WEB_MA1out", false),
		41:  NewBool("ID_WEB_MZ1out", false),
		42:  NewBool("ID_WEB_VENout", false),
		43:  NewBool("ID_WEB_VBOout", false),
		44:  NewBool("ID_WEB_VD1out", false),
		45:  NewBool("ID_WEB_VD2out", false),
		46:  NewBool("ID_WEB_ZIPout", false),
		47:  NewBool("ID_WEB_ZUPout", false),
		48:  NewBool("ID_WEB_ZW1out", false),
		49:  NewBool("ID_WEB_ZW2SSTout", false),
		50:  NewBool("ID_WEB_ZW3SSTout", false),
		51:  NewBool("ID_WEB_FP2out", false),
		52:  NewBool("ID_WEB_SLPout", false),
		53:  NewBool("ID_WEB_SUPout", false),
		54:  NewBool("ID_WEB_MZ2out", false),
		55:  NewBool("ID_WEB_MA2out", false),
		56:  NewSeconds("ID_WEB_Zaehler_BetrZeitVD1"),
		57:  NewCount("ID_WEB_Zaehler_BetrZeitImpVD1"),
		58:  NewSeconds("ID_WEB_Zaehler_BetrZeitVD2"),
		59:  NewCount("ID_WEB_Zaehler_BetrZeitImpVD2"),
		60:  NewSeconds("ID_WEB_Zaehler_BetrZeitZWE1"),
		61:  NewSeconds("ID_WEB_Zaehler_BetrZeitZWE2"),
		62:  NewSeconds("ID_WEB_Zaehler_BetrZeitZWE3"),
		63:  NewSeconds("ID_WEB_Zaehler_BetrZeitWP"),
		64:  NewSeconds("ID_WEB_Zaehler_BetrZeitHz"),
		65:  NewSeconds("ID_WEB_Zaehler_BetrZeitBW"),
		66:  NewSeconds("ID_WEB_Zaehler_BetrZeitKue"),
		67:  NewSeconds("ID_WEB_Time_WPein_akt"),
		68:  NewSeconds("ID_WEB_Time_ZWE1_akt"),
		69:  NewSeconds("ID_WEB_Time_ZWE2_akt"),
		70:  NewSeconds("ID_WEB_Timer_EinschVerz"),
		71:  NewSeconds("ID_WEB_Time_SSPAUS_akt"),
		72:  NewSeconds("ID_WEB_Time_SSPEIN_akt"),
		73:  NewSeconds("ID_WEB_Time_VDStd_akt"),
		74:  NewSeconds("ID_WEB_Time_HRM_akt"),
		75:  NewSeconds("ID_WEB_Time_HRW_akt"),
		76:  NewSeconds("ID_WEB_Time_LGS_akt"),
		77:  NewSeconds("ID_WEB_Time_SBW_akt"),
		78:  NewHeatpumpCode("ID_WEB_Code_WP_akt"), // heat pump type; internal type 3
		79:  NewBivalenceLevel("ID_WEB_BIV_Stufe_akt"),
		80:  NewOperationMode("ID_WEB_WP_BZ_akt"),
		81:  NewCharacter("ID_WEB_SoftStand_0"),
		82:  NewCharacter("ID_WEB_SoftStand_1"),
		83:  NewCharacter("ID_WEB_SoftStand_2"),
		84:  NewCharacter("ID_WEB_SoftStand_3"),
		85:  NewCharacter("ID_WEB_SoftStand_4"),
		86:  NewCharacter("ID_WEB_SoftStand_5"),
		87:  NewCharacter("ID_WEB_SoftStand_6"),
		88:  NewCharacter("ID_WEB_SoftStand_7"),
		89:  NewCharacter("ID_WEB_SoftStand_8"),
		90:  NewCharacter("ID_WEB_SoftStand_9"),
		91:  NewIPV4Address("ID_WEB_AdresseIP_akt"),
		92:  NewIPV4Address("ID_WEB_SubNetMask_akt"),
		93:  NewIPV4Address("ID_WEB_Add_Broadcast"),
		94:  NewIPV4Address("ID_WEB_Add_StdGateway"),
		95:  NewTime("ID_WEB_ERROR_Time0"),
		96:  NewTime("ID_WEB_ERROR_Time1"),
		97:  NewTime("ID_WEB_ERROR_Time2"),
		98:  NewTime("ID_WEB_ERROR_Time3"),
		99:  NewTime("ID_WEB_ERROR_Time4"),
		100: NewErrorcode("ID_WEB_ERROR_Nr0"),
		101: NewErrorcode("ID_WEB_ERROR_Nr1"),
		102: NewErrorcode("ID_WEB_ERROR_Nr2"),
		103: NewErrorcode("ID_WEB_ERROR_Nr3"),
		104: NewErrorcode("ID_WEB_ERROR_Nr4"),
		105: NewCount("ID_WEB_AnzahlFehlerInSpeicher"),
		106: NewSwitchoffFile("ID_WEB_Switchoff_file_Nr0"),
		107: NewSwitchoffFile("ID_WEB_Switchoff_file_Nr1"),
		108: NewSwitchoffFile("ID_WEB_Switchoff_file_Nr2"),
		109: NewSwitchoffFile("ID_WEB_Switchoff_file_Nr3"),
		110: NewSwitchoffFile("ID_WEB_Switchoff_file_Nr4"),
		111: NewTime("ID_WEB_Switchoff_file_Time0"),
		112: NewTime("ID_WEB_Switchoff_file_Time1"),
		113: NewTime("ID_WEB_Switchoff_file_Time2"),
		114: NewTime("ID_WEB_Switchoff_file_Time3"),
		115: NewTime("ID_WEB_Switchoff_file_Time4"),
		116: NewBool("ID_WEB_Comfort_exists", false),
		117: NewMainMenuStatusLine1("ID_WEB_HauptMenuStatus_Zeile1"),
		118: NewMainMenuStatusLine2("ID_WEB_HauptMenuStatus_Zeile2"),
		119: NewMainMenuStatusLine3("ID_WEB_HauptMenuStatus_Zeile3"),
		120: NewSeconds("ID_WEB_HauptMenuStatus_Zeit"),
		121: NewLevel("ID_WEB_HauptMenuAHP_Stufe"),
		122: NewCelsius("ID_WEB_HauptMenuAHP_Temp", false),
		123: NewSeconds("ID_WEB_HauptMenuAHP_Zeit"),
		124: NewBool("ID_WEB_SH_BWW", false),
		125: NewIcon("ID_WEB_SH_HZ"),
		126: NewIcon("ID_WEB_SH_MK1"),
		127: NewIcon("ID_WEB_SH_MK2"),
		128: NewUnknown("ID_WEB_Einst_Kurzrpgramm"),
		129: NewUnknown("ID_WEB_StatusSlave_1"),
		130: NewUnknown("ID_WEB_StatusSlave_2"),
		131: NewUnknown("ID_WEB_StatusSlave_3"),
		132: NewUnknown("ID_WEB_StatusSlave_4"),
		133: NewUnknown("ID_WEB_StatusSlave_5"),
		134: NewTime("ID_WEB_AktuelleTimeStamp"),
		135: NewIcon("ID_WEB_SH_MK3"),
		136: NewCelsius("ID_WEB_Sollwert_TVL_MK3", false),
		137: NewCelsius("ID_WEB_Temperatur_TFB3", false),
		138: NewBool("ID_WEB_MZ3out", false),
		139: NewBool("ID_WEB_MA3out", false),
		140: NewBool("ID_WEB_FP3out", false),
		141: NewSeconds("ID_WEB_Time_AbtIn"),
		142: NewCelsius("ID_WEB_Temperatur_RFV2", false),
		143: NewCelsius("ID_WEB_Temperatur_RFV3", false),
		144: NewIcon("ID_WEB_SH_SW"),
		145: NewUnknown("ID_WEB_Zaehler_BetrZeitSW"),
		146: NewBool("ID_WEB_FreigabKuehl", false),
		147: NewVoltage("ID_WEB_AnalogIn"),
		148: NewUnknown("ID_WEB_SonderZeichen"),
		149: NewIcon("ID_WEB_SH_ZIP"),
		150: NewIcon("ID_WEB_WebsrvProgrammWerteBeobarten"),
		151: NewEnergy("ID_WEB_WMZ_Heizung"),
		152: NewEnergy("ID_WEB_WMZ_Brauchwasser"),
		153: NewEnergy("ID_WEB_WMZ_Schwimmbad"),
		154: NewEnergy("ID_WEB_WMZ_Seit"),
		155: NewFlow("ID_WEB_WMZ_Durchfluss"),
		156: NewVoltage("ID_WEB_AnalogOut1"),
		157: NewVoltage("ID_WEB_AnalogOut2"),
		158: NewSeconds("ID_WEB_Time_Heissgas"),
		159: NewCelsius("ID_WEB_Temp_Lueftung_Zuluft", false),
		160: NewCelsius("ID_WEB_Temp_Lueftung_Abluft", false),
		161: NewSeconds("ID_WEB_Zaehler_BetrZeitSolar"),
		162: NewVoltage("ID_WEB_AnalogOut3"),
		163: NewVoltage("ID_WEB_AnalogOut4"),
		164: NewVoltage("ID_WEB_Out_VZU"),
		165: NewVoltage("ID_WEB_Out_VAB"),
		166: NewBool("ID_WEB_Out_VSK", false),
		167: NewBool("ID_WEB_Out_FRH", false),
		168: NewVoltage("ID_WEB_AnalogIn2"),
		169: NewVoltage("ID_WEB_AnalogIn3"),
		170: NewBool("ID_WEB_SAXin", false),
		171: NewBool("ID_WEB_SPLin", false),
		172: NewBool("ID_WEB_Compact_exists", false),
		173: NewFlow("ID_WEB_Durchfluss_WQ"),
		174: NewBool("ID_WEB_LIN_exists", false),
		175: NewCelsius("ID_WEB_LIN_ANSAUG_VERDAMPFER", false),
		176: NewCelsius("ID_WEB_LIN_ANSAUG_VERDICHTER", false),
		177: NewCelsius("ID_WEB_LIN_VDH", false),
		178: NewKelvin("ID_WEB_LIN_UH", false),
		179: NewKelvin("ID_WEB_LIN_UH_Soll", false),
		180: NewPressure("ID_WEB_LIN_HD"),
		181: NewPressure("ID_WEB_LIN_ND"),
		182: NewBool("ID_WEB_LIN_VDH_out", false),
		183: NewPercent2("ID_WEB_HZIO_PWM"),
		184: NewSpeed("ID_WEB_HZIO_VEN"),
		185: NewUnknown("ID_WEB_HZIO_EVU2"),
		186: NewBool("ID_WEB_HZIO_STB", false),
		187: NewEnergy("ID_WEB_SEC_Qh_Soll"),
		188: NewEnergy("ID_WEB_SEC_Qh_Ist"),
		189: NewCelsius("ID_WEB_SEC_TVL_Soll", false),
		190: NewUnknown("ID_WEB_SEC_Software"),
		191: NewSecOperationMode("ID_WEB_SEC_BZ"),
		192: NewUnknown("ID_WEB_SEC_VWV"),
		193: NewSpeed("ID_WEB_SEC_VD"),
		194: NewCelsius("ID_WEB_SEC_VerdEVI", false),
		195: NewCelsius("ID_WEB_SEC_AnsEVI", false),
		196: NewKelvin("ID_WEB_SEC_UEH_EVI", false),
		197: NewKelvin("ID_WEB_SEC_UEH_EVI_S", false),
		198: NewCelsius("ID_WEB_SEC_KondTemp", false),
		199: NewCelsius("ID_WEB_SEC_FlussigEx", false),
		200: NewCelsius("ID_WEB_SEC_UK_EEV", false),
		201: NewPressure("ID_WEB_SEC_EVI_Druck"),
		202: NewVoltage("ID_WEB_SEC_U_Inv"),
		203: NewCelsius("ID_WEB_Temperatur_THG_2", false),
		204: NewCelsius("ID_WEB_Temperatur_TWE_2", false),
		205: NewCelsius("ID_WEB_LIN_ANSAUG_VERDAMPFER_2", false),
		206: NewCelsius("ID_WEB_LIN_ANSAUG_VERDICHTER_2", false),
		207: NewCelsius("ID_WEB_LIN_VDH_2", false),
		208: NewKelvin("ID_WEB_LIN_UH_2", false),
		209: NewKelvin("ID_WEB_LIN_UH_Soll_2", false),
		210: NewPressure("ID_WEB_LIN_HD_2"),
		211: NewPressure("ID_WEB_LIN_ND_2"),
		212: NewBool("ID_WEB_HDin_2", false),
		213: NewBool("ID_WEB_AVout_2", false),
		214: NewBool("ID_WEB_VBOout_2", false),
		215: NewBool("ID_WEB_VD1out_2", false),
		216: NewBool("ID_WEB_LIN_VDH_out_2", false),
		217: NewSwitchoffFile("ID_WEB_Switchoff2_file_Nr0"),
		218: NewSwitchoffFile("ID_WEB_Switchoff2_file_Nr1"),
		219: NewSwitchoffFile("ID_WEB_Switchoff2_file_Nr2"),
		220: NewSwitchoffFile("ID_WEB_Switchoff2_file_Nr3"),
		221: NewSwitchoffFile("ID_WEB_Switchoff2_file_Nr4"),
		222: NewTime("ID_WEB_Switchoff2_file_Time0"),
		223: NewTime("ID_WEB_Switchoff2_file_Time1"),
		224: NewTime("ID_WEB_Switchoff2_file_Time2"),
		225: NewTime("ID_WEB_Switchoff2_file_Time3"),
		226: NewTime("ID_WEB_Switchoff2_file_Time4"),
		227: NewCelsius("ID_WEB_RBE_RT_Ist", false),
		228: NewCelsius("ID_WEB_RBE_RT_Soll", false),
		229: NewCelsius("ID_WEB_Temperatur_BW_oben", false),
		230: NewHeatpumpCode("ID_WEB_Code_WP_akt_2"),
		231: NewFrequency("ID_WEB_Freq_VD"),
		232: NewCelsius("Vapourisation_Temperature", false),
		233: NewCelsius("Liquefaction_Temperature", false),
		234: NewUnknown("Unknown_Calculation_234"),
		235: NewUnknown("Unknown_Calculation_235"),
		236: NewFrequency("ID_WEB_Freq_VD_Soll"),
		237: NewFrequency("ID_WEB_Freq_VD_Min"),
		238: NewFrequency("ID_WEB_Freq_VD_Max"),
		239: NewKelvin("VBO_Temp_Spread_Soll", false),
		240: NewKelvin("VBO_Temp_Spread_Ist", false),
		241: NewPercent2("HUP_PWM"),
		242: NewKelvin("HUP_Temp_Spread_Soll", false),
		243: NewKelvin("HUP_Temp_Spread_Ist", false),
		244: NewUnknown("Unknown_Calculation_244"),
		245: NewUnknown("Unknown_Calculation_245"),
		246: NewUnknown("Unknown_Calculation_246"),
		247: NewUnknown("Unknown_Calculation_247"),
		248: NewUnknown("Unknown_Calculation_248"),
		249: NewUnknown("Unknown_Calculation_249"),
		250: NewUnknown("Unknown_Calculation_250"),
		251: NewUnknown("Unknown_Calculation_251"),
		252: NewUnknown("Unknown_Calculation_252"),
		253: NewUnknown("Unknown_Calculation_253"),
		254: NewFlow("Flow_Rate_254"),
		255: NewUnknown("Unknown_Calculation_255"),
		256: NewUnknown("Unknown_Calculation_256"),
		257: NewPower("Heat_Output"),
		258: NewMajorMinorVersion("RBE_Version"),
		259: NewUnknown("Unknown_Calculation_259"),
		260: NewUnknown("Unknown_Calculation_260"),
		261: NewUnknown("Unknown_Calculation_261"),
		262: NewUnknown("Unknown_Calculation_262"),
		263: NewUnknown("Unknown_Calculation_263"),
		264: NewUnknown("Unknown_Calculation_264"),
		265: NewUnknown("Unknown_Calculation_265"),
		266: NewUnknown("Unknown_Calculation_266"),
		267: NewUnknown("Unknown_Calculation_267"), // Desired Room Temperature ?
	}
}
